repos:
-   hooks:
    -   id: pre-commit-update
        args:
        -   --verbose
    repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.3.2
-   hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
-   hooks:
    -   id: ruff
        args:
        -   --config=pyproject.toml
        -   --fix
        -   --exit-non-zero-on-fix
        types_or: [python, pyi, jupyter]
    -   id: ruff-format
        args:
        -   --config=pyproject.toml
        types_or: [python, pyi, jupyter]
    repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.6
-   hooks:
    -   id: mypy
        args:
        -   --config=pyproject.toml
        additional_dependencies:
        -   types-pytz
        -   types-python-dateutil
        -   types-decorator
        -   types-protobuf
        -   types-pytz
        -   types-requests
        -   types-setuptools
        -   types-six
        -   types-ujson
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
-   hooks:
    -   id: pylint
        name: pylint
        entry: .venv/bin/pylint
        language: system
        types: [python]
        args:
        -   --rcfile=pyproject.toml
        -   --load-plugins=databricks.labs.pylint.all
    repo: local
-   hooks:
    -   id: pytest-unit-tests
        name: pytest-unit-tests
        args: [./tests/unit/]
        entry: bash -c 'source ./.venv/bin/activate && pytest'
        language: system
        pass_filenames: false
        stages: [commit]
    repo: local
